### ISSUE TITLE
Add an example project?

### ISSUE THREAD

**Issue by Sweeper777** [iosphere/ISHHoverBar#10]
After reading the README file, I don't really understand how to use this thing. Can you please show some example code in the README or add an example project?

**Comment by felixLam** [comment]
Hi @Sweeper777,

there is one in the repo in the `SampleApp` folder:
https://github.com/iosphere/ISHHoverBar/tree/master/SampleApp

Kind regards,

Felix

**Comment by Sweeper777** [comment]
Oh I see! Sorry I didn't see it at first!
