### ISSUE TITLE
Draw the image with the tint color of the UIBarButton!

### ISSUE THREAD

**Issue by Sweeper777** [iosphere/ISHHoverBar#14]
Even if I set an all black image like this one as the image of a `UIBarButtonItem`:

![camera_000000_25](https://cloud.githubusercontent.com/assets/13585047/21956881/efad2684-da81-11e6-8e6c-1851169ac341.png)

iOS will still draw the image as if it were all white if the `tintColor` is white. Can you replicate this behaviour of `UIBarButtonItem`?

**Comment by felixLam** [comment]
Have you tried setting the image rendering mode explicitly to always use the original and never template mode?

**Comment by Sweeper777** [comment]
How can I set that?

**Comment by felixLam** [comment]
You can set this in the right side pane of the asset catalog or via code.

**Comment by felixLam** [comment]
Check out the UIImage documentation
